# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_resultswindow.ui',
# licensing of 'ui_resultswindow.ui' applies.
#
# Created: Mon Apr 22 02:23:08 2019
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(863, 401)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mplCanvasWidget = MyMplCanvasWidget(self.groupBox)
        self.mplCanvasWidget.setObjectName("mplCanvasWidget")
        self.gridLayout_2.addWidget(self.mplCanvasWidget, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 4)
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setInvertedAppearance(False)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.gridLayout_3.addWidget(self.horizontalScrollBar, 1, 0, 1, 4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_X_Day = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_X_Day.setObjectName("radioButton_X_Day")
        self.gridLayout.addWidget(self.radioButton_X_Day, 0, 0, 1, 1)
        self.radioButton_X_Week = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_X_Week.setObjectName("radioButton_X_Week")
        self.gridLayout.addWidget(self.radioButton_X_Week, 1, 0, 1, 1)
        self.radioButton_X_Month = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_X_Month.setObjectName("radioButton_X_Month")
        self.gridLayout.addWidget(self.radioButton_X_Month, 2, 0, 1, 1)
        self.radioButton_X_Custom = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_X_Custom.setObjectName("radioButton_X_Custom")
        self.gridLayout.addWidget(self.radioButton_X_Custom, 3, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.dateEdit_From_Date = QtWidgets.QDateEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_From_Date.sizePolicy().hasHeightForWidth())
        self.dateEdit_From_Date.setSizePolicy(sizePolicy)
        self.dateEdit_From_Date.setReadOnly(False)
        self.dateEdit_From_Date.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateEdit_From_Date.setCalendarPopup(False)
        self.dateEdit_From_Date.setObjectName("dateEdit_From_Date")
        self.horizontalLayout.addWidget(self.dateEdit_From_Date)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.dateEdit_To_Date = QtWidgets.QDateEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_To_Date.sizePolicy().hasHeightForWidth())
        self.dateEdit_To_Date.setSizePolicy(sizePolicy)
        self.dateEdit_To_Date.setCalendarPopup(False)
        self.dateEdit_To_Date.setObjectName("dateEdit_To_Date")
        self.horizontalLayout.addWidget(self.dateEdit_To_Date)
        self.gridLayout_3.addWidget(self.groupBox_3, 2, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.comboBox_Y_Subplot_1 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_Y_Subplot_1.setObjectName("comboBox_Y_Subplot_1")
        self.gridLayout_4.addWidget(self.comboBox_Y_Subplot_1, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 1, 1)
        self.comboBox_Y_Subplot_2 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_Y_Subplot_2.setObjectName("comboBox_Y_Subplot_2")
        self.gridLayout_4.addWidget(self.comboBox_Y_Subplot_2, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 2, 0, 1, 1)
        self.comboBox_Y_Subplot_3 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_Y_Subplot_3.setObjectName("comboBox_Y_Subplot_3")
        self.gridLayout_4.addWidget(self.comboBox_Y_Subplot_3, 2, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_4, 2, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(575, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 2, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 863, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Graph", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "X-axis", None, -1))
        self.radioButton_X_Day.setText(QtWidgets.QApplication.translate("MainWindow", "Day", None, -1))
        self.radioButton_X_Week.setText(QtWidgets.QApplication.translate("MainWindow", "Week", None, -1))
        self.radioButton_X_Month.setText(QtWidgets.QApplication.translate("MainWindow", "Month", None, -1))
        self.radioButton_X_Custom.setText(QtWidgets.QApplication.translate("MainWindow", "Custom", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "Custom X-axis Scope", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "From", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "To", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("MainWindow", "Y-axis", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Graph 1", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Graph 2", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Graph 3", None, -1))

from view.resultswindow.localwidgets.mymplcanvaswidget import MyMplCanvasWidget
